Cleanup
gridcapacitymap/gridcapacity pull request #5
Opened 2023-09-27 14:34 UTC by dmy3k

2023-09-27 15:56 UTC, Zagryzyn approved these changes

2023-09-27 18:03 UTC, dvlazariev requested changes

2023-09-27 18:03 UTC, dvlazariev commented on gridcapacity/output.py
> +        return Path(__file__).absolute().parents[1]
That was an intended behavior. And how a case path could be a directory?

2023-09-28 09:13 UTC, dvlazariev approved these changes

2023-09-28 09:13 UTC, dvlazariev commented on gridcapacity/output.py
> +        return case_path if case_path.is_dir() else case_path.parent
```suggestion
        return case_path.parent
```

2023-09-28 09:14 UTC, dvlazariev commented on gridcapacity/output.py
> +        return Path(__file__).absolute().parents[1]
OK, there was a bug.

2023-09-28 09:22 UTC, dmy3k commented on gridcapacity/output.py
> +        return case_path if case_path.is_dir() else case_path.parent
Agreed to simplify a bit

```suggestion
        return case_path.parent
```

2023-09-28 09:23 UTC, merged